sudo: required

dist: trusty

os: 
  - linux
  - osx

language: cpp

compiler: gcc

notifications:
  email:
    recipients:
      - giadaloopmachine@gmail.com
    on_success: never
    on_failure: always

before_install:

  - ./.travis/before_install.sh

install:

  - ./.travis/install.sh

before_script:

  - ./.travis/before_script.sh

script: make && make check

after_failure: cat $TRAVIS_BUILD_DIR/test-suite.log
