sudo: required

dist: trusty

language: cpp

compiler: gcc

notifications:
  email:
    recipients:
      - giadaloopmachine@gmail.com
    on_success: never
    on_failure: always

before_install:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y # for gcc 6
  - sudo apt-get update -qq
  - sudo apt-get install -y gcc-6 g++-6 libsndfile1-dev libsamplerate0-dev libfltk1.3-dev libasound2-dev libxpm-dev libpulse-dev libjack-dev libxrandr-dev libx11-dev libxinerama-dev libxcursor-dev

before_script:

  # Download and build latest version of RtMidi

  - wget http://www.music.mcgill.ca/~gary/rtmidi/release/rtmidi-2.1.0.tar.gz
  - tar -xvf rtmidi-2.1.0.tar.gz
  - cd rtmidi-2.1.0 && ./configure --with-jack --with-alsa && make && sudo make install || true
  - cd ..

  # Download and install latest version of Jansson

  - wget http://www.digip.org/jansson/releases/jansson-2.7.tar.gz
  - tar -xvf jansson-2.7.tar.gz
  - cd jansson-2.7 && ./configure && make && sudo make install || true
  - sudo ldconfig
  - cd ..

  # Download midimaps package for testing purposes

  - wget https://github.com/monocasual/giada-midimaps/archive/master.zip -O giada-midimaps-master.zip
  - unzip giada-midimaps-master.zip
  - mkdir -p $HOME/.giada/midimaps
  - cp giada-midimaps-master/midimaps/* $HOME/.giada/midimaps

  # Download vst plugin for testing purposes

  - wget http://www.discodsp.com/download/?id=18 -O bliss-linux.zip
  - unzip bliss-linux.zip -d bliss-linux
  - cp bliss-linux/64-bit/Bliss64Demo.so .

  # Build Giada. Note the CFLAGS: optimization levels are set to O1 in order
  # not to throw up nasty errors from JUCE modules.

  - ./autogen.sh
  - ./configure CXXFLAGS='-g -O1' --target=linux --enable-vst

script: make && make check

after_failure: cat $TRAVIS_BUILD_DIR/test-suite.log
