language: cpp

compiler: gcc

notifications: 
  email:
    recipients:
      - giadaloopmachine@gmail.com
    on_success: never
    on_failure: always

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y libsndfile1-dev libsamplerate0-dev libfltk1.3-dev libasound2-dev libxpm-dev libpulse-dev libjack-dev

before_script: 
  - wget http://www.music.mcgill.ca/~gary/rtmidi/release/rtmidi-2.1.0.tar.gz
  - tar -xvf rtmidi-2.1.0.tar.gz
  - cd rtmidi-2.1.0 && ./configure --with-jack --with-alsa && make && sudo make install || true 
  - cd ..
  - ./autogen.sh
  - ./configure --target=linux --enable-vst

script: make
